### ISSUE TITLE
Fix deprecated actions

### ISSUE THREAD

**Issue by nexus49** [openmfp/gha#64]
Artifact actions v3 will be deprecated by December 5, 2024. You are receiving this email because you have GitHub Actions workflows using v3 of [actions/upload-artifact](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapp.github.media%2Fe%2Fer%3Fs%3D88570519%26lid%3D6648%26elqTrackId%3Dd2da2b8a2e2546f6bbbefc4362a25248%26elq%3D701531a4e23f4b32b6175b153bba28d9%26elqaid%3D4245%26elqat%3D1%26elqak%3D8AF5A79567D1D842C6394C4E2A26BD2485A914ADB0801B1DFF5CA3389F4A143B31FF&data=05%7C02%7Cbastian.echterhoelter%40sap.com%7C511d3a14e444451336d108dcfdeff940%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C638664454324315540%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=AawnyVg7O%2Flqgk6GMuIlgSBEze9397iVOxLdgRu%2FJqc%3D&reserved=0) or [actions/download-artifact](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapp.github.media%2Fe%2Fer%3Fs%3D88570519%26lid%3D6647%26elqTrackId%3Da0c373a95cb941a69247c326aef08dfe%26elq%3D701531a4e23f4b32b6175b153bba28d9%26elqaid%3D4245%26elqat%3D1%26elqak%3D8AF5A416F3461CA0C91DF8AF94CEC73EC20A14ADB0801B1DFF5CA3389F4A143B31FF&data=05%7C02%7Cbastian.echterhoelter%40sap.com%7C511d3a14e444451336d108dcfdeff940%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C638664454324333441%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=OEfZAelFqInLI4cDnz%2BG%2BAmZLAWGukGwbAFQeY3s9x8%3D&reserved=0). After this date using v3 of these actions will result in a workflow failure. Artifacts within their retention period will remain accessible from the UI or REST API regardless of the version used to upload.

To raise awareness of the upcoming removal, we will temporarily fail jobs using v3 of actions/upload-artifact or actions/download-artifact. Builds that are scheduled to run during the brownout periods will fail. The brownouts are scheduled for the following dates and times:

November 14, 12pm - 1pm EST
November 21, 9am - 5pm EST
What you need to do
Update workflows to begin using v4 of the artifact actions as soon as possible. While v4 improves upload and download speeds by up to 98% and includes several new features, there are [key differences](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapp.github.media%2Fe%2Fer%3Fs%3D88570519%26lid%3D6646%26elqTrackId%3Dd75d31293f0e47148c8f2a339957fcaf%26elq%3D701531a4e23f4b32b6175b153bba28d9%26elqaid%3D4245%26elqat%3D1%26elqak%3D8AF52EF15428B1DCF971E377BBEBF230341A14ADB0801B1DFF5CA3389F4A143B31FF&data=05%7C02%7Cbastian.echterhoelter%40sap.com%7C511d3a14e444451336d108dcfdeff940%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C638664454324351045%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=9GpZ0Jw4tF8OYPTj2kMOTCVlDWjboXjXg2RV3KHYSAU%3D&reserved=0) from previous versions that may require updates to your workflows. Please see [the documentation](https://eur03.safelinks.protection.outlook.com/?url=https%3A%2F%2Fapp.github.media%2Fe%2Fer%3Fs%3D88570519%26lid%3D6645%26elqTrackId%3D53ce96ddadbb4fe1951a5a31db6a10b3%26elq%3D701531a4e23f4b32b6175b153bba28d9%26elqaid%3D4245%26elqat%3D1%26elqak%3D8AF5B7CF2FDD10084FA269DD666DEC9DD40F14ADB0801B1DFF5CA3389F4A143B31FF&data=05%7C02%7Cbastian.echterhoelter%40sap.com%7C511d3a14e444451336d108dcfdeff940%7C42f7676cf455423c82f6dc2d99791af7%7C0%7C0%7C638664454324367256%7CUnknown%7CTWFpbGZsb3d8eyJFbXB0eU1hcGkiOnRydWUsIlYiOiIwLjAuMDAwMCIsIlAiOiJXaW4zMiIsIkFOIjoiTWFpbCIsIldUIjoyfQ%3D%3D%7C0%7C%7C%7C&sdata=QIQRvMzCAIOxTDeF2UQ3%2BgZ1ZnfhNeHCdo53VLXD2F4%3D&reserved=0) in the project repositories for guidance on how to migrate your workflows.

**Comment by akafazov** [comment]
@nexus49 both download and upload-artefact have been updated to v4 by renovate
